name: Build H5P content type

on:
  workflow_call:
    inputs:
      expected-unsafe-translations:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check translations with H5P-CLI
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/h5p-check-translations.sh"
          "${GITHUB_WORKSPACE}/.github/scripts/h5p-check-translations.sh"

      - name: Install node modules from package.json
        run: |
          if [ -f "./package.json" ]
          then
            npm ci
          fi

      - name: Lint
        run: |
          if [ -f "./package.json" ]
          then
            npm run lint --if-present
          fi

      - name: Build
        run: |
          if [ -f "./package.json" ]
          then
            npm run build --if-present
          fi
